# Generated by Django 5.2.8 on 2025-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=100, verbose_name='選手名')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日付')),
                ('physical_fatigue', models.PositiveSmallIntegerField(verbose_name='身体疲労度 (0-10)')),
                ('mental_fatigue', models.PositiveSmallIntegerField(verbose_name='精神的疲労度 (0-10)')),
                ('training_completion', models.PositiveSmallIntegerField(verbose_name='トレーニング達成率 (0-100)')),
                ('heart_rate', models.PositiveSmallIntegerField(verbose_name='心拍数')),
                ('diary', models.TextField(blank=True, verbose_name='今日の練習日誌')),
            ],
            options={
                'ordering': ['-date', 'athlete_name'],
            },
        ),
    ]
